authors:
  mathiol:
    name: BORDIER-AUPY Mathieu
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/68553121
  mathchameleon:
    name: LIAIGRE Mathéo
    description: Contributor
    avatar: https://avatars.githubusercontent.com/u/147376380
